import express from 'express';
import CountriesController from '../controllers/countriesController.js';

const router = express.Router();

/**
 * @openapi
 * components:
 *   schemas:
 *     Country:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           format: int32
 *         name:
 *           type: string
 *         code:
 *           type: string
 *         flag:
 *           type: string
 *         created_at:
 *           type: string
 *           format: date-time
 *         updated_at:
 *           type: string
 *           format: date-time
 *       required:
 *         - name
 */

// Routes for Countries (English documentation)

/**
 * @openapi
 * /api/countries:
 *   get:
 *     summary: Get a list of all countries
 *     tags:
 *       - Countries
 *     description: Returns an array of country objects.
 *     responses:
 *       200:
 *         description: A JSON array of countries
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Country'
 *             example: [{ "id": 1, "name": "England", "code": "ENG", "flag": "url/to/flag.png" }]
 *       500:
 *         description: Internal Server Error
 */
router.get('/countries', CountriesController.getAllCountries);          // GET /api/countries

/**
 * @openapi
 * /api/countries/{id}:
 *   get:
 *     summary: Get a single country by ID
 *     tags:
 *       - Countries
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *           format: int32
 *         description: The ID of the country to retrieve
 *     responses:
 *       200:
 *         description: Country object
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Country'
 *             example: { "id": 1, "name": "England", "code": "ENG", "flag": "url/to/flag.png" }
 *       404:
 *         description: Country not found
 *       500:
 *         description: Internal Server Error
 */
router.get('/countries/:id', CountriesController.getCountryById);      // GET /api/countries/:id

/**
 * @openapi
 * /api/countries:
 *   post:
 *     summary: Create a new country
 *     tags:
 *       - Countries
 *     requestBody:
 *       description: Country object to create (id is generated by the database)
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               name:
 *                 type: string
 *               code:
 *                 type: string
 *               flag:
 *                 type: string
 *             required:
 *               - name
 *           example:
 *             name: "England"
 *             code: "ENG"
 *             flag: "https://example.com/flags/eng.png"
 *     responses:
 *       201:
 *         description: Country created successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Country'
 *             example: { "id": 123, "name": "England", "code": "ENG", "flag": "https://example.com/flags/eng.png" }
 *       400:
 *         description: Bad Request (invalid input)
 *       500:
 *         description: Internal Server Error
 */
router.post('/countries', CountriesController.createCountry);          // POST /api/countries

/**
 * @openapi
 * /api/countries/{id}:
 *   put:
 *     summary: Update an existing country by ID
 *     tags:
 *       - Countries
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *           format: int32
 *         description: The ID of the country to update
 *     requestBody:
 *       description: Partial or full country object to update
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Country'
 *           example: { "name": "England", "code": "ENG" }
 *     responses:
 *       200:
 *         description: Country updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Country'
 *       400:
 *         description: Bad Request (invalid input)
 *       404:
 *         description: Country not found
 *       500:
 *         description: Internal Server Error
 */
router.put('/countries/:id', CountriesController.updateCountry);       // PUT /api/countries/:id

/**
 * @openapi
 * /api/countries/{id}:
 *   delete:
 *     summary: Delete a country by ID
 *     tags:
 *       - Countries
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *           format: int32
 *         description: The ID of the country to delete
 *     responses:
 *       200:
 *         description: Country deleted successfully
 *       404:
 *         description: Country not found
 *       500:
 *         description: Internal Server Error
 */
router.delete('/countries/:id', CountriesController.deleteCountry);    // DELETE /api/countries/:id

/**
 * @openapi
 * /api/countries/import:
 *   post:
 *     summary: Import countries from the external API-Football and save to database
 *     tags:
 *       - Countries
 *     description: Fetches country data from API-Football and inserts or updates records in the local database.
 *     responses:
 *       200:
 *         description: Import completed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                 imported:
 *                   type: integer
 *             example: { "message": "Import completed", "imported": 42 }
 *       500:
 *         description: Internal Server Error
 */
router.post('/countries/import', CountriesController.importFromApiFootball); // POST /api/countries/import

export default router;